### ISSUE TITLE
cannot import name 'Evolutionary' from 'stochopy'

### ISSUE THREAD

**Issue by SeismoZhou** [keurfonluu/stochopy#10]
Hi keurfonluu,

Thank you for sharing such a wonderful package!

I try to use the your dispersion inversion code, and find that there is a problem with:
`from stochopy import Evolutionary
`
`ImportError: cannot import name 'Evolutionary' from 'stochopy' (~/.conda/envs/pg/lib/python3.8/site-packages/stochopy/__init__.py)`

I installed evodcinv with pip. and the version of stochopy is (2.0.1)

Do you know where this problem might come from? 

Thanks in advance.

Kind regards,
Wen

**Comment by keurfonluu** [comment]
Hi @SeismoZhou ,

Apology, I haven't updated `evodcinv` to the latest version of `stochopy` which breaks compatibility.
Please downgrade `stochopy` to version `1.7.3`.

```
pip install stochopy==1.7.3
```

I'll try to update `evodcinv` when I have more free time to spare.

**Comment by SeismoZhou** [comment]
Thank you very much for the response! 
When downgraded stochopy, the inversion starts working!

All the best!
Wen
